# Lab 8: Define and Solve an ML Problem of Your Choosing

In [2]:
import pandas as pd
import numpy as np
import os 
import matplotlib.pyplot as plt
import seaborn as sns

In this lab assignment, you will follow the machine learning life cycle and implement a model to solve a machine learning problem of your choosing. You will select a data set and choose a predictive problem that the data set supports.  You will then inspect the data with your problem in mind and begin to formulate a  project plan. You will then implement the machine learning project plan. 

You will complete the following tasks:

1. Build Your DataFrame
2. Define Your ML Problem
3. Perform exploratory data analysis to understand your data.
4. Define Your Project Plan
5. Implement Your Project Plan:
    * Prepare your data for your model.
    * Fit your model to the training data and evaluate your model.
    * Improve your model's performance.

## Part 1: Build Your DataFrame

You will have the option to choose one of four data sets that you have worked with in this program:

* The "census" data set that contains Census information from 1994: `censusData.csv`
* Airbnb NYC "listings" data set: `airbnbListingsData.csv`
* World Happiness Report (WHR) data set: `WHR2018Chapter2OnlineData.csv`
* Book Review data set: `bookReviewsData.csv`

Note that these are variations of the data sets that you have worked with in this program. For example, some do not include some of the preprocessing necessary for specific models. 

#### Load a Data Set and Save it as a Pandas DataFrame

The code cell below contains filenames (path + filename) for each of the four data sets available to you.

<b>Task:</b> In the code cell below, use the same method you have been using to load the data using `pd.read_csv()` and save it to DataFrame `df`. 

You can load each file as a new DataFrame to inspect the data before choosing your data set.

In [3]:
# File names of the four data sets
adultDataSet_filename = os.path.join(os.getcwd(), "data", "censusData.csv")
#airbnbDataSet_filename = os.path.join(os.getcwd(), "data", "airbnbListingsData.csv")
#WHRDataSet_filename = os.path.join(os.getcwd(), "data", "WHR2018Chapter2OnlineData.csv")
#bookReviewDataSet_filename = os.path.join(os.getcwd(), "data", "bookReviewsData.csv")


df = pd.read_csv(adultDataSet_filename) 

df.head(10)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex_selfID,capital-gain,capital-loss,hours-per-week,native-country,income_binary
0,39.0,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Non-Female,2174,0,40.0,United-States,<=50K
1,50.0,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Non-Female,0,0,13.0,United-States,<=50K
2,38.0,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Non-Female,0,0,40.0,United-States,<=50K
3,53.0,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Non-Female,0,0,40.0,United-States,<=50K
4,28.0,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40.0,Cuba,<=50K
5,37.0,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40.0,United-States,<=50K
6,49.0,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16.0,Jamaica,<=50K
7,52.0,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Non-Female,0,0,45.0,United-States,>50K
8,31.0,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50.0,United-States,>50K
9,42.0,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Non-Female,5178,0,40.0,United-States,>50K

## Part 2: Define Your ML Problem

Next you will formulate your ML Problem. In the markdown cell below, answer the following questions:

1. List the data set you have chosen.
2. What will you be predicting? What is the label?
3. Is this a supervised or unsupervised learning problem? Is this a clustering, classification or regression problem? Is it a binary classificaiton or multi-class classifiction problem?
4. What are your features? (note: this list may change after your explore your data)
5. Explain why this is an important problem. In other words, how would a company create value with a model that predicts this label?

1. We chose the census dataset
2. We will be predicting whether a given person has a yearly salary of more than or less than 50k. The label is income_binary. 
3. This is a supervised learning problem, and a logistic regression problem.
4. Features are age, workclass, education-num, marital-status, occupation, race, sex_selfID, hours-per-week, native-country
5. This is important to know what types of people are making less than or more than 50k (a somewhat livable wage). This could be important for politics, so a polititian knows what percentage of their constituency is poor so that they can tailor policies that will benefit potential voters.

## Part 3: Understand Your Data

The next step is to perform exploratory data analysis. Inspect and analyze your data set with your machine learning problem in mind. Consider the following as you inspect your data:

1. What data preparation techniques would you like to use? These data preparation techniques may include:

    * addressing missingness, such as replacing missing values with means
    * finding and replacing outliers
    * renaming features and labels
    * finding and replacing outliers
    * performing feature engineering techniques such as one-hot encoding on categorical features
    * selecting appropriate features and removing irrelevant features
    * performing specific data cleaning and preprocessing techniques for an NLP problem
    * addressing class imbalance in your data sample to promote fair AI
    

2. What machine learning model (or models) you would like to use that is suitable for your predictive problem and data?
    * Are there other data preparation techniques that you will need to apply to build a balanced modeling data set for your problem and model? For example, will you need to scale your data?
 
 
3. How will you evaluate and improve the model's performance?
    * Are there specific evaluation metrics and methods that are appropriate for your model?
    

Think of the different techniques you have used to inspect and analyze your data in this course. These include using Pandas to apply data filters, using the Pandas `describe()` method to get insight into key statistics for each column, using the Pandas `dtypes` property to inspect the data type of each column, and using Matplotlib and Seaborn to detect outliers and visualize relationships between features and labels. If you are working on a classification problem, use techniques you have learned to determine if there is class imbalance.

<b>Task</b>: Use the techniques you have learned in this course to inspect and analyze your data. You can import additional packages that you have used in this course that you will need to perform this task.

<b>Note</b>: You can add code cells if needed by going to the <b>Insert</b> menu and clicking on <b>Insert Cell Below</b> in the drop-drown menu.

In [4]:

features_drop = ['fnlwgt', 'education', 'relationship', 'capital-gain', 'capital-loss']
df =df.drop(features_drop, axis = 1)
df.columns

Index(['age', 'workclass', 'education-num', 'marital-status', 'occupation',
       'race', 'sex_selfID', 'hours-per-week', 'native-country',
       'income_binary'],
      dtype='object')

In [5]:
print(df.columns)
corr_matrix = round(df.corr(),5)
corr_matrix

Index(['age', 'workclass', 'education-num', 'marital-status', 'occupation',
       'race', 'sex_selfID', 'hours-per-week', 'native-country',
       'income_binary'],
      dtype='object')

                    age  education-num  hours-per-week
age             1.00000        0.03676         0.06707
education-num   0.03676        1.00000         0.14726
hours-per-week  0.06707        0.14726         1.00000

In [6]:

nan_count = np.sum(df.isnull(), axis = 0)
nan_detected = nan_count != 0 
#print(nan_detected) 
is_int_or_float = (df.dtypes == 'int64')| (df.dtypes == 'float64')
to_impute = nan_detected & is_int_or_float
print(to_impute) 
cols_to_impute = list(df.columns[to_impute])
print(cols_to_impute)

age                True
workclass         False
education-num     False
marital-status    False
occupation        False
race              False
sex_selfID        False
hours-per-week     True
native-country    False
income_binary     False
dtype: bool
['age', 'hours-per-week']

In [7]:
for x in cols_to_impute: 
    name = x+"_na"
    df[name] = df[x].isnull()
print(df.columns)

Index(['age', 'workclass', 'education-num', 'marital-status', 'occupation',
       'race', 'sex_selfID', 'hours-per-week', 'native-country',
       'income_binary', 'age_na', 'hours-per-week_na'],
      dtype='object')

In [8]:
for x in cols_to_impute: 
    df[x].fillna(value = df[x].mean(), inplace = True)
print(df.head(10))

    age         workclass  education-num         marital-status  \
0  39.0         State-gov             13          Never-married
1  50.0  Self-emp-not-inc             13     Married-civ-spouse
2  38.0           Private              9               Divorced
3  53.0           Private              7     Married-civ-spouse
4  28.0           Private             13     Married-civ-spouse
5  37.0           Private             14     Married-civ-spouse
6  49.0           Private              5  Married-spouse-absent
7  52.0  Self-emp-not-inc              9     Married-civ-spouse
8  31.0           Private             14          Never-married
9  42.0           Private             13     Married-civ-spouse

          occupation   race  sex_selfID  hours-per-week native-country  \
0       Adm-clerical  White  Non-Female            40.0  United-States
1    Exec-managerial  White  Non-Female            13.0  United-States
2  Handlers-cleaners  White  Non-Female            40.0  United-States
3  Handlers-cleaners  Black  Non-Female            40.0  United-States
4     Prof-specialty  Black      Female            40.0           Cuba
5    Exec-managerial  White      Female            40.0  United-States
6      Other-service  Black      Female            16.0        Jamaica
7    Exec-managerial  White  Non-Female            45.0  United-States
8     Prof-specialty  White      Female            50.0  United-States
9    Exec-managerial  White  Non-Female            40.0  United-States

  income_binary  age_na  hours-per-week_na
0         <=50K   False              False
1         <=50K   False              False
2         <=50K   False              False
3         <=50K   False              False
4         <=50K   False              False
5         <=50K   False              False
6         <=50K   False              False
7          >50K   False              False
8          >50K   False              False
9          >50K   False              False

In [9]:
df.rename(columns = {'income_binary' : 'income_above50k?'}, inplace = True)
df.columns

Index(['age', 'workclass', 'education-num', 'marital-status', 'occupation',
       'race', 'sex_selfID', 'hours-per-week', 'native-country',
       'income_above50k?', 'age_na', 'hours-per-week_na'],
      dtype='object')

In [10]:
df.replace({'income_above50k?': {'>50K': True, '<=50K': False}}, inplace = True)
df.head(10)

,age,workclass,education-num,marital-status,occupation,race,sex_selfID,hours-per-week,native-country,income_above50k?,age_na,hours-per-week_na
0,39.0,State-gov,13,Never-married,Adm-clerical,White,Non-Female,40.0,United-States,False,False,False
1,50.0,Self-emp-not-inc,13,Married-civ-spouse,Exec-managerial,White,Non-Female,13.0,United-States,False,False,False
2,38.0,Private,9,Divorced,Handlers-cleaners,White,Non-Female,40.0,United-States,False,False,False
3,53.0,Private,7,Married-civ-spouse,Handlers-cleaners,Black,Non-Female,40.0,United-States,False,False,False
4,28.0,Private,13,Married-civ-spouse,Prof-specialty,Black,Female,40.0,Cuba,False,False,False
5,37.0,Private,14,Married-civ-spouse,Exec-managerial,White,Female,40.0,United-States,False,False,False
6,49.0,Private,5,Married-spouse-absent,Other-service,Black,Female,16.0,Jamaica,False,False,False
7,52.0,Self-emp-not-inc,9,Married-civ-spouse,Exec-managerial,White,Non-Female,45.0,United-States,True,False,False
8,31.0,Private,14,Never-married,Prof-specialty,White,Female,50.0,United-States,True,False,False
9,42.0,Private,13,Married-civ-spouse,Exec-managerial,White,Non-Female,40.0,United-States,True,False,False

In [11]:
feature_list = [x for x in df if x != 'income_above50k?']
#print(feature_list)
df_onehot = [x for x in feature_list if df[x].dtype == 'object']
print(df_onehot)

['workclass', 'marital-status', 'occupation', 'race', 'sex_selfID', 'native-country']

In [12]:
df['workclass'].fillna(value = "workclass_unavailable", inplace = True)
#df['workclass'].unique()
df["workclass"] = df["workclass"].replace(["Without-pay", "Never-worked"], "No-income")
#df['workclass'].head()
df['workclass'].unique()

array(['State-gov', 'Self-emp-not-inc', 'Private', 'Federal-gov',
       'Local-gov', 'workclass_unavailable', 'Self-emp-inc', 'No-income'],
      dtype=object)

In [13]:
df_workclass = pd.get_dummies(data = df['workclass'])
df_workclass.index = df.index

In [14]:
df = pd.concat([df, df_workclass], axis = 1)
df = df.drop('workclass', axis = 1)

In [15]:
df.head(10)

,age,education-num,marital-status,occupation,race,sex_selfID,hours-per-week,native-country,income_above50k?,age_na,hours-per-week_na,Federal-gov,Local-gov,No-income,Private,Self-emp-inc,Self-emp-not-inc,State-gov,workclass_unavailable
0,39.0,13,Never-married,Adm-clerical,White,Non-Female,40.0,United-States,False,False,False,0,0,0,0,0,0,1,0
1,50.0,13,Married-civ-spouse,Exec-managerial,White,Non-Female,13.0,United-States,False,False,False,0,0,0,0,0,1,0,0
2,38.0,9,Divorced,Handlers-cleaners,White,Non-Female,40.0,United-States,False,False,False,0,0,0,1,0,0,0,0
3,53.0,7,Married-civ-spouse,Handlers-cleaners,Black,Non-Female,40.0,United-States,False,False,False,0,0,0,1,0,0,0,0
4,28.0,13,Married-civ-spouse,Prof-specialty,Black,Female,40.0,Cuba,False,False,False,0,0,0,1,0,0,0,0
5,37.0,14,Married-civ-spouse,Exec-managerial,White,Female,40.0,United-States,False,False,False,0,0,0,1,0,0,0,0
6,49.0,5,Married-spouse-absent,Other-service,Black,Female,16.0,Jamaica,False,False,False,0,0,0,1,0,0,0,0
7,52.0,9,Married-civ-spouse,Exec-managerial,White,Non-Female,45.0,United-States,True,False,False,0,0,0,0,0,1,0,0
8,31.0,14,Never-married,Prof-specialty,White,Female,50.0,United-States,True,False,False,0,0,0,1,0,0,0,0
9,42.0,13,Married-civ-spouse,Exec-managerial,White,Non-Female,40.0,United-States,True,False,False,0,0,0,1,0,0,0,0

In [16]:
df['marital-status'].unique()
df['marital-status'].fillna(value = 'marital-status_unavailable', inplace = True)

In [17]:
df_marital_status = pd.get_dummies(data = df['marital-status'])
df_marital_status.index = df.index

In [18]:
df = pd.concat([df, df_marital_status], axis = 1)
df = df.drop('marital-status', axis = 1)

In [19]:
df.columns

Index(['age', 'education-num', 'occupation', 'race', 'sex_selfID',
       'hours-per-week', 'native-country', 'income_above50k?', 'age_na',
       'hours-per-week_na', 'Federal-gov', 'Local-gov', 'No-income', 'Private',
       'Self-emp-inc', 'Self-emp-not-inc', 'State-gov',
       'workclass_unavailable', 'Divorced', 'Married-AF-spouse',
       'Married-civ-spouse', 'Married-spouse-absent', 'Never-married',
       'Separated', 'Widowed'],
      dtype='object')

In [20]:
#'occupation', 'race', 'sex_selfID', 'native-country']
df['occupation'].unique()
df['occupation'].fillna(value = 'occupation_unavailable', inplace = True)
df_occupation = pd.get_dummies(data = df['occupation'])
df_occupation.index = df.index

In [21]:
df = pd.concat([df, df_occupation], axis = 1)
df = df.drop('occupation', axis = 1)

In [22]:
df.columns

Index(['age', 'education-num', 'race', 'sex_selfID', 'hours-per-week',
       'native-country', 'income_above50k?', 'age_na', 'hours-per-week_na',
       'Federal-gov', 'Local-gov', 'No-income', 'Private', 'Self-emp-inc',
       'Self-emp-not-inc', 'State-gov', 'workclass_unavailable', 'Divorced',
       'Married-AF-spouse', 'Married-civ-spouse', 'Married-spouse-absent',
       'Never-married', 'Separated', 'Widowed', 'Adm-clerical', 'Armed-Forces',
       'Craft-repair', 'Exec-managerial', 'Farming-fishing',
       'Handlers-cleaners', 'Machine-op-inspct', 'Other-service',
       'Priv-house-serv', 'Prof-specialty', 'Protective-serv', 'Sales',
       'Tech-support', 'Transport-moving', 'occupation_unavailable'],
      dtype='object')

In [23]:
#df['race'].unique()
df['race'].fillna(value = "race_unavailable", inplace = True)
df_race = pd.get_dummies(data = df['race'])
df_race.index = df.index

In [24]:
df = pd.concat([df, df_race], axis = 1)
df = df.drop('race', axis = 1)

In [25]:
df.columns

Index(['age', 'education-num', 'sex_selfID', 'hours-per-week',
       'native-country', 'income_above50k?', 'age_na', 'hours-per-week_na',
       'Federal-gov', 'Local-gov', 'No-income', 'Private', 'Self-emp-inc',
       'Self-emp-not-inc', 'State-gov', 'workclass_unavailable', 'Divorced',
       'Married-AF-spouse', 'Married-civ-spouse', 'Married-spouse-absent',
       'Never-married', 'Separated', 'Widowed', 'Adm-clerical', 'Armed-Forces',
       'Craft-repair', 'Exec-managerial', 'Farming-fishing',
       'Handlers-cleaners', 'Machine-op-inspct', 'Other-service',
       'Priv-house-serv', 'Prof-specialty', 'Protective-serv', 'Sales',
       'Tech-support', 'Transport-moving', 'occupation_unavailable',
       'Amer-Indian-Inuit', 'Asian-Pac-Islander', 'Black', 'Other', 'White'],
      dtype='object')

In [26]:
#df['sex_selfID'].unique()
df['sex_selfID'].fillna(value = 'sex_selfID_unavailable', inplace= True)
df['sex_selfID'].unique()

array(['Non-Female', 'Female'], dtype=object)

In [27]:
df_sex_selfID = pd.get_dummies(data = df['sex_selfID'])
df_sex_selfID.index = df.index

In [28]:
df = pd.concat([df, df_sex_selfID], axis = 1)
df = df.drop('sex_selfID', axis = 1)

In [29]:
df['native-country'].unique()
df['native-country'].fillna(value = 'native-country_unavailable', inplace = True)

In [30]:
df.replace({'native-country': {'Hong': 'Hong Kong', 'Holand-Netherlands': 'Netherlands', 'Outlying-US(Guam-USVI-etc)': 'US territories', 'South': 'South Africa', 'Yugoslavia': 'Former-Yugoslavia', 'Columbia': 'Colombia', 'Trinadad&Tobago': 'Trinidad&Tobago'}}, inplace = True)

In [31]:
df['native-country'].fillna(value = 'native-country-unavilable', inplace = True)

In [32]:
df['native-country'] = df['native-country'].replace(['Mexico', 'Honduras', 'Guatemala', 'Nicaragua', 'El-Salvador'], "Central America")
df['native-country'] = df['native-country'].replace(['Peru', 'Colombia', 'Ecuador'], 'South America')

In [33]:
df['native-country'] = df['native-country'].replace(['Jamaica', 'Haiti', 'Cuba', 'Dominican-Republic', 'Trinidad&Tobago', 'Puerto-Rico'], 'Caribbean')

In [34]:
df['native-country'] = df['native-country'].replace(['Laos', 'Thailand', 'Vietnam', 'Cambodia', 'Philippines'], 'South East Asia')

In [35]:
df['native-country'] = df['native-country'].replace(['China', 'Japan', 'Hong Kong', 'Taiwan'], 'East Asia')

In [36]:
df['native-country'] = df['native-country'].replace(['Italy', 'Portugal', 'Greece'], 'South Europe')

In [37]:
df['native-country'] = df['native-country'].replace(['Poland', 'Former-Yugoslavia', 'Hungary'], 'East Europe')

In [38]:
df['native-country'] = df['native-country'].replace(['France', 'Germany', 'Netherlands'], 'West Europe')

In [39]:
df['native-country'] = df['native-country'].replace(['England', 'Scotland'], 'UK')
df.replace({'native-country': {'Ireland': 'Republic of Ireland'}}, inplace = True)

In [40]:
df_native_country = pd.get_dummies(data = df['native-country'])
df_native_country.index = df.index

In [41]:
df = pd.concat([df, df_native_country], axis = 1)
df = df.drop('native-country', axis = 1)

## Part 4: Define Your Project Plan

Now that you understand your data, in the markdown cell below, define your plan to implement the remaining phases of the machine learning life cycle (data preparation, modeling, evaluation) to solve your ML problem. Answer the following questions:

* Do you have a new feature list? If so, what are the features that you chose to keep and remove after inspecting the data? 
* Explain different data preparation techniques that you will use to prepare your data for modeling.
* What is your model (or models)?
* Describe your plan to train your model, analyze its performance and then improve the model. That is, describe your model building, validation and selection plan to produce a model that generalizes well to new data.

1. Yes, we have a new feature list. We decided to remove the columns fnlwgt, education, relationship, capital-gain, and capital-loss. After inspecting the data, we couldn't figure out what fnlwgt meant, education was rendered redundant by the presence of education_num, and capital-gain and capital-loss seemed unrelated to our problem statement.
2. I'll need to one hot encode workclass, marital-status, occupation and sex_selfID
3. I'll use the logistic regression model
4. I will train a logistic regression model on the data set, evaluate its performance, iterate through different hyperparameter values of C for loss.

## Part 5: Implement Your Project Plan

<b>Task:</b> In the code cell below, import additional packages that you have used in this course that you will need to implement your project plan.

In [42]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split 
from sklearn.metrics import log_loss
from sklearn.metrics import accuracy_score

<b>Task:</b> Use the rest of this notebook to carry out your project plan. 

You will:

1. Prepare your data for your model.
2. Fit your model to the training data and evaluate your model.
3. Improve your model's performance by performing model selection and/or feature selection techniques to find best model for your problem.

Add code cells below and populate the notebook with commentary, code, analyses, results, and figures as you see fit.

In [43]:
feature_list = [x for x in df if x != 'income_above50k?']

In [44]:
y = df['income_above50k?']
X = df[feature_list]
print("Number of examples: " + str(X.shape[0]))
print("\nNumber of Features:" + str(X.shape[1]))

Number of examples: 32561

Number of Features:59

In [45]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1234)

In [46]:
lr_sk = LogisticRegression(max_iter=100**10)
lr_sk.fit(X,y)

LogisticRegression(max_iter=100000000000000000000)

In [47]:

print('The fitted weights and intercept with sklearn are:')
print(lr_sk.coef_, lr_sk.intercept_)

The fitted weights and intercept with sklearn are:
[[ 0.02908626  0.29794524  0.03001565  0.07543177  0.13093463  0.33492889
  -0.30941133 -1.30290438 -0.0947363   0.17825302 -0.51239874 -0.46481239
  -0.31389559 -0.91585344  1.4387186   1.15081679 -0.84776703 -1.37582607
  -1.01523062 -0.91983505  0.04690138 -0.36125519  0.06109112  0.8303605
  -0.99023305 -0.69647964 -0.28928002 -0.85137313 -1.78533988  0.62219534
   0.52897251  0.2944411   0.61902693 -0.12189117 -0.39211362 -0.72464903
  -0.30314733 -0.40428075 -0.7687032  -0.28419651 -1.32907532 -1.15590149
   0.26064654 -0.15237033 -0.47460283 -0.14131865 -0.09586439 -0.39201039
   0.02047879  0.24725585 -0.69279925 -1.10654663  0.10090235  0.24231519
   0.19255162 -0.83482543  0.1296719   0.37646054 -0.16492169]] [-5.70939982]

In [48]:
%timeit lr_sk.fit(X,y)

2.57 s ± 50.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [49]:
# Make predictions
y_pred = lr_sk.predict(X_test)

In [50]:

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
#conf_matrix = confusion_matrix(y_test, y_pred)
#class_report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
#print("Confusion Matrix:")
#print(conf_matrix)
#print("Classification Report:")
#print(class_report)

Accuracy: 0.8294249022892239